version: "3.8"

# add restart related commands to the different containers
services:
  web:
    build: ./MiniTrello
    # TODO: break this into multilines
    command: sh -c "python3 manage.py makemigrations && python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && gunicorn --config gunicorn_config.py"
    volumes:
      - ./MiniTrello/:/app/
      - static_volume:/app/staticfiles/
    expose:
      - 8000
    env_file:
      - .env
    restart: always

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/staticfiles/
    depends_on:
      - web
    restart: on-failure

volumes:
  static_volume:
